version: '3.9'

services:

  ids.admin:
    image: 'saintogod/ids-admin'
    build:
      context: .
      dockerfile: src/Admin/Dockerfile
    container_name: ids-admin
    hostname: ids-admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ids.sts
    volumes:
      - './shared/serilog.json:/usr/share/Saintogod/serilog.json'
      - './shared/identitydata.json:/usr/share/Saintogod/identitydata.json'
      - './shared/identityserverdata.json:/usr/share/Saintogod/identityserverdata.json'
      - './shared/dev.crt:/etc/saintogod/dev.crt'
      - './shared/dev.key:/etc/saintogod/dev.key'
    networks:
      - saintogod

  ids.admin.api:
    image: 'saintogod/ids-admin-api'
    build:
      context: .
      dockerfile: src/Admin.Api/Dockerfile
    container_name: ids-admin-api
    hostname: ids-admin-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/usr/share/Saintogod/serilog.json'
      - './shared/dev.crt:/etc/saintogod/dev.crt'
      - './shared/dev.key:/etc/saintogod/dev.key'
    networks:
      - saintogod
    depends_on:
      - ids.sts

  ids.sts:
    image: 'saintogod/ids-sts'
    build:
      context: .
      dockerfile: src/STS.Identity/Dockerfile
    container_name: ids-sts
    hostname: ids-sts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/usr/share/Saintogod/serilog.json'
      - './shared/dev.crt:/etc/saintogod/dev.crt'
      - './shared/dev.key:/etc/saintogod/dev.key'
    networks:
      - saintogod

networks:
  saintogod:
    name: saintogod
    external: true
