version: '3.9'

services:

  ids.admin:
    image: 'saintogod/ids-admin'
    build:
      context: .
      dockerfile: src/Admin/Dockerfile
    container_name: ids-admin
    hostname: ids-admin
    environment:
      - AdminConfiguration__IdentityAdminRedirectUri=https://admin.saintogod.local/signin-oidc
      - AdminConfiguration__IdentityServerBaseUrl=https://sso.saintogod.local
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ids.sts
    volumes:
      - './shared/serilog.json:/usr/share/st.ids/serilog.json'
      - './shared/deployment.json:/usr/share/st.ids/deployment.json'
      - './shared/identitydata.json:/usr/share/st.ids/identitydata.json'
      - './shared/identityserverdata.json:/usr/share/st.ids/identityserverdata.json'
      - './shared/dev.crt:/etc/st.ids/dev.crt'
      - './shared/dev.key:/etc/st.ids/dev.key'
    networks:
      - saintogod

  ids.admin.api:
    image: 'saintogod/ids-admin-api'
    build:
      context: .
      dockerfile: src/Admin.Api/Dockerfile
    container_name: ids-admin-api
    hostname: ids-admin-api
    environment:
      - AdminApiConfiguration__ApiBaseUrl=https://admin-api.saintogod.local
      - AdminApiConfiguration__IdentityServerBaseUrl=https://sso.saintogod.local
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/usr/share/st.ids/serilog.json'
      - './shared/deployment.json:/usr/share/st.ids/deployment.json'
      - './shared/dev.crt:/etc/st.ids/dev.crt'
      - './shared/dev.key:/etc/st.ids/dev.key'
    networks:
      - saintogod
    depends_on:
      - ids.sts

  ids.sts:
    image: 'saintogod/ids-sts'
    build:
      context: .
      dockerfile: src/STS.Identity/Dockerfile
    container_name: ids-sts
    hostname: ids-sts
    environment:
      - AdminConfiguration__IdentityAdminBaseUrl=https://admin.saintogod.local
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/usr/share/st.ids/serilog.json'
      - './shared/deployment.json:/usr/share/st.ids/deployment.json'
      - './shared/dev.crt:/etc/st.ids/dev.crt'
      - './shared/dev.key:/etc/st.ids/dev.key'
    networks:
      - saintogod

networks:
  saintogod:
    name: saintogod
    external: true
